#!/bin/bash
make
for var in {1..21}
	do
		awk -v V="$var" 'BEGIN{printf "\n\n\t========%d========\n\n", V}'
		sleep 1
		./philo 11 610 200 200 10 > output
		bytes=$(cat output | grep "seg" | wc -l)
		if [[ "$bytes" -ne "0" ]]; then
			break
		fi
		cat output
	done
